name: HFT-Sim

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check_cc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install formatters
      run: pip install -r requirements.txt

    - name: Check cmake formatting
      run: gersemi --config .gersemi_config.json --check --diff cmake/ CMakeLists.txt src/

    - name: Check C++ formatting
      run: find src/cpp -type f -iname "*.cpp" -o -iname "*.hpp" | xargs clang-format --style=file:.clang-format --dry-run --fail-on-incomplete-format
  build:
    runs-on: ubuntu-latest
    needs: check_cc
    name: ${{ matrix.build_type }} build

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}}

